// A library of complete 40-question listening tests the teacher can load into
// the question builder with one click and then edit freely. Each template
// mirrors the structure of a real academic listening paper (part layout,
// question types, instruction formats) with original sample content the
// teacher replaces with their own material — and their own audio recording.
//
// Every loaded template is ordinary builder state: sections can be deleted,
// reordered or moved between parts, MCQ questions added/removed, options
// edited one-per-line, or a whole part replaced by pasting into a new
// "pasted" section with numbered placeholders (e.g. 31_____).

import type { AuthoredTest } from "./authoring";
import { GAP_TOKEN } from "./authoring";

const G = GAP_TOKEN;

export type ListeningTemplate = {
  id: string;
  /** Shown in the template picker. */
  label: string;
  test: AuthoredTest;
};

// ============================================================================
// Template 1 — notes · MCQ · matching · choose TWO
// ============================================================================

const TEMPLATE_1: AuthoredTest = {
  module: "listening",
  name: "Full Listening Test — Sample 1",
  status: "draft",
  startNumber: 1,
  groups: [
    {
      id: "t1-p1-notes",
      type: "pasted",
      part: 1,
      instructions: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
      text: [
        "Westbury Market — customer survey",
        "The customer travels to the market by 1_____.",
        "She comes to the market mainly to buy fresh 2_____ and bread.",
        "Her favourite stall sells secondhand 3_____.",
        "She thinks the market needs more 4_____ for visitors.",
        "She would like the market to stay open later on 5_____ evenings.",
        "Customer's family name: 6_____",
        "Contact number: 7_____",
        "She first heard about the market from a 8_____.",
        "She agrees to answer a longer survey by 9_____.",
        "As a thank-you she will receive a free 10_____.",
      ].join("\n\n"),
    },
    {
      id: "t1-p2-mcq",
      type: "mcq",
      variant: "single",
      part: 2,
      instructions: "Choose the correct letter, A, B or C.",
      questions: [
        {
          stem: "Why was the sports centre closed for part of last year?",
          options: [
            "The building was damaged in a storm.",
            "Major rebuilding work was carried out.",
            "A new owner took over the site.",
          ].join("\n"),
        },
        {
          stem: "What is new about the swimming pool?",
          options: [
            "It is now heated all year.",
            "It has a separate area for young children.",
            "It is open for longer hours.",
          ].join("\n"),
        },
        {
          stem: "Members are asked to book classes",
          options: ["at the reception desk.", "through the centre's app.", "by telephone."].join("\n"),
        },
        {
          stem: "What does the speaker say about parking?",
          options: [
            "It is free for members in the evenings.",
            "The car park has been made larger.",
            "Staff can no longer park on site.",
          ].join("\n"),
        },
      ],
    },
    {
      id: "t1-p2-match",
      type: "drag-text",
      part: 2,
      instructions:
        "What change has been made in each area of the sports centre? Choose SIX answers from the box and drag the correct answer next to questions 15–20.",
      title: "Areas of the sports centre",
      text: [
        `Gym ${G}`,
        `Café ${G}`,
        `Tennis courts ${G}`,
        `Changing rooms ${G}`,
        `Dance studio ${G}`,
        `Climbing wall ${G}`,
      ].join("\n\n"),
      options: [
        "new equipment",
        "bigger space",
        "improved lighting",
        "new flooring",
        "redecorated",
        "longer opening hours",
        "extra staff",
        "new heating system",
      ].join("\n"),
    },
    {
      id: "t1-p3-double",
      type: "mcq",
      variant: "double",
      part: 3,
      instructions: "Choose TWO letters, A–E.",
      questions: [
        {
          stem: "Which TWO things do the students agree were strengths of their survey?",
          options: [
            "The questions were short.",
            "The sample size was large.",
            "Responses were collected quickly.",
            "The questions avoided technical language.",
            "The survey reached a range of age groups.",
          ].join("\n"),
        },
        {
          stem: "Which TWO problems did the students have when analysing their results?",
          options: [
            "Some answers were incomplete.",
            "The software kept crashing.",
            "They ran out of time.",
            "Two questions were misunderstood.",
            "Their notes were disorganised.",
          ].join("\n"),
        },
      ],
    },
    {
      id: "t1-p3-mcq",
      type: "mcq",
      variant: "single",
      part: 3,
      instructions: "Choose the correct letter, A, B or C.",
      questions: [
        {
          stem: "The students decide to begin their presentation with",
          options: ["a short video.", "a question for the audience.", "a summary of their findings."].join("\n"),
        },
        {
          stem: "What does the tutor advise them to do next?",
          options: ["collect more data", "rewrite their introduction", "check their references"].join("\n"),
        },
      ],
    },
    {
      id: "t1-p3-match",
      type: "drag-text",
      part: 3,
      instructions:
        "Which section of the report will the students put each type of information in? Choose FOUR answers from the box and drag the correct answer next to questions 27–30.",
      title: "Types of information",
      text: [
        `Interview quotations ${G}`,
        `Response statistics ${G}`,
        `Questionnaire design ${G}`,
        `Suggestions for further research ${G}`,
      ].join("\n\n"),
      options: ["introduction", "methods", "results", "discussion", "conclusion", "appendix"].join("\n"),
    },
    {
      id: "t1-p4-notes",
      type: "pasted",
      part: 4,
      instructions: "Complete the notes below. Write ONE WORD ONLY for each answer.",
      text: [
        "Street trees in cities",
        "Benefits",
        "In summer, trees lower the 31_____ of the air in city streets.",
        "Trees trap some of the 32_____ produced by traffic.",
        "The presence of trees can reduce levels of 33_____ among city residents.",
        "Streets with trees encourage people to travel by 34_____ or on foot.",
        "Problems",
        "Tree roots can damage 35_____ under the street.",
        "Falling 36_____ can block drains in autumn.",
        "The pollen of some species causes 37_____ in some people.",
        "Care",
        "Young trees need regular 38_____ during dry periods.",
        "Cities now prefer species that can survive periods of 39_____.",
        "Sensors placed in the 40_____ send data about each tree's health.",
      ].join("\n\n"),
    },
  ],
  answersRaw: [
    "bus",
    "vegetables",
    "books",
    "parking",
    "Friday",
    "Paxton",
    "07700 900452 / 07700900452",
    "neighbour / neighbor",
    "email",
    "calendar",
    "B",
    "B",
    "B",
    "A",
    "new equipment",
    "bigger space",
    "improved lighting",
    "new flooring",
    "redecorated",
    "longer opening hours",
    "B / D",
    "B / D",
    "A / D",
    "A / D",
    "B",
    "C",
    "discussion",
    "results",
    "methods",
    "conclusion",
    "temperature",
    "dust",
    "stress",
    "bicycle / bike",
    "pipes",
    "leaves",
    "allergies",
    "watering",
    "drought",
    "soil",
  ].join("\n"),
};

// ============================================================================
// Template 2 — notes · MCQ · map labelling · choose TWO · matching
// ============================================================================

const TEMPLATE_2: AuthoredTest = {
  module: "listening",
  name: "Full Listening Test — Sample 2",
  status: "draft",
  startNumber: 1,
  groups: [
    {
      id: "t2-p1-notes",
      type: "pasted",
      part: 1,
      instructions: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
      text: [
        "Redwell Country Park — visitor information",
        "The main entrance is on Mill 1_____.",
        "Parking costs £ 2_____ per day.",
        "The 3_____ trail is suitable for wheelchairs.",
        "Bird hides are located beside the 4_____.",
        "The visitor centre sells locally produced 5_____.",
        "Rangers lead free walks every 6_____ morning.",
        "The adventure playground is made entirely of 7_____.",
        "Dogs must be kept on a 8_____ near the farm animals.",
        "The café is closed during 9_____.",
        "To book an event, phone 10_____.",
      ].join("\n\n"),
    },
    {
      id: "t2-p2-mcq",
      type: "mcq",
      variant: "single",
      part: 2,
      instructions: "Choose the correct letter, A, B or C.",
      questions: [
        {
          stem: "This year's festival will take place in",
          options: ["the market square.", "the school grounds.", "the riverside park."].join("\n"),
        },
        {
          stem: "The festival will open with",
          options: ["a parade.", "a concert.", "a fireworks display."].join("\n"),
        },
        {
          stem: "Profits from the festival will go to",
          options: ["the town library.", "a children's charity.", "the sports club."].join("\n"),
        },
        {
          stem: "Volunteers should sign up",
          options: ["online.", "at the town hall.", "by phone."].join("\n"),
        },
        {
          stem: "The organisers still need help with",
          options: ["car parking.", "serving food.", "clearing up."].join("\n"),
        },
      ],
    },
    {
      id: "t2-p2-map",
      type: "special",
      part: 2,
      instructions: "Label the map below. Write the correct letter, A–H, next to questions 16–20.",
      elements: { picture: true, table: true, drag: false, options: false },
      rows: ["16 Main stage", "17 Craft tent", "18 First aid point", "19 Food stalls", "20 Lost property"].join("\n"),
      cols: ["A", "B", "C", "D", "E", "F", "G", "H"].join("\n"),
    },
    {
      id: "t2-p3-double",
      type: "mcq",
      variant: "double",
      part: 3,
      instructions: "Choose TWO letters, A–E.",
      questions: [
        {
          stem: "Which TWO ingredients did the students decide to leave out of their recipe trials?",
          options: ["salt", "butter", "nuts", "honey", "cream"].join("\n"),
        },
        {
          stem: "Which TWO aspects of the packaging do the students agree need improving?",
          options: ["the size", "the colours", "the material", "the labelling", "the cost"].join("\n"),
        },
      ],
    },
    {
      id: "t2-p3-match",
      type: "drag-text",
      part: 3,
      instructions:
        "How do the students feel about each stage of their project? Choose SIX answers from the box and drag the correct answer next to questions 25–30.",
      title: "Stages of the project",
      text: [
        `Choosing the topic ${G}`,
        `Background reading ${G}`,
        `Designing the survey ${G}`,
        `Testing the recipes ${G}`,
        `Analysing the feedback ${G}`,
        `Writing the report ${G}`,
      ].join("\n\n"),
      options: [
        "it took longer than expected",
        "it was enjoyable",
        "it needs to be repeated",
        "it was harder than expected",
        "it produced surprising results",
        "it required outside help",
        "it was well organised",
        "it should have been started earlier",
      ].join("\n"),
    },
    {
      id: "t2-p4-notes",
      type: "pasted",
      part: 4,
      instructions: "Complete the notes below. Write ONE WORD ONLY for each answer.",
      text: [
        "The Aldmoor stone circle excavation",
        "Discovery",
        "The site was found when a farmer was digging a 31_____.",
        "The circle was originally surrounded by a wooden 32_____.",
        "Fragments of 33_____ show that people cooked at the site.",
        "Construction",
        "The stones were probably moved on wooden 34_____.",
        "Analysis of ancient 35_____ revealed which crops were grown nearby.",
        "One burial contained beads made of 36_____.",
        "The site may have been abandoned because of changes in the 37_____.",
        "The site today",
        "Visitors follow a raised 38_____ around the circle.",
        "A digital 39_____ of the site can be explored online.",
        "Archaeologists still hope to locate the builders' 40_____.",
      ].join("\n\n"),
    },
  ],
  answersRaw: [
    "Lane",
    "4.50",
    "lake",
    "marsh",
    "honey",
    "Saturday",
    "wood",
    "lead / leash",
    "January",
    "01632 960555",
    "C",
    "A",
    "B",
    "A",
    "C",
    "F",
    "B",
    "H",
    "D",
    "A",
    "C / E",
    "C / E",
    "B / D",
    "B / D",
    "it was enjoyable",
    "it took longer than expected",
    "it was well organised",
    "it produced surprising results",
    "it was harder than expected",
    "it should have been started earlier",
    "ditch",
    "fence",
    "pottery",
    "sledges",
    "seeds",
    "amber",
    "climate",
    "walkway",
    "model",
    "village",
  ].join("\n"),
};

// ============================================================================
// Template 3 — notes · choose TWO · matching · MCQ · matching · notes
// ============================================================================

const TEMPLATE_3: AuthoredTest = {
  module: "listening",
  name: "Full Listening Test — Sample 3",
  status: "draft",
  startNumber: 1,
  groups: [
    {
      id: "t3-p1-notes",
      type: "pasted",
      part: 1,
      instructions: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
      text: [
        "Starting work at Brightside Insurance",
        "New employees should arrive at the 1_____ entrance.",
        "Ask for the training officer, whose surname is 2_____.",
        "The induction talk begins at 3_____.",
        "Bring a form of 4_____, for example a passport.",
        "A temporary 5_____ will be provided for the first week.",
        "Lunch can be bought in the 6_____ on the top floor.",
        "The building has a free 7_____ for staff.",
        "Wednesday's training session covers using the phone 8_____.",
        "New staff receive a discount of 9_____ % in the shop downstairs.",
        "Any questions should be emailed to the 10_____ department.",
      ].join("\n\n"),
    },
    {
      id: "t3-p2-double",
      type: "mcq",
      variant: "double",
      part: 2,
      instructions: "Choose TWO letters, A–E.",
      questions: [
        {
          stem: "Which TWO things should new members bring to their first club ride?",
          options: ["a repair kit", "a route map", "food for the day", "spare clothing", "a water bottle"].join("\n"),
        },
        {
          stem: "Which TWO changes to the club does the speaker announce?",
          options: [
            "a new meeting place",
            "higher membership fees",
            "weekend trips away",
            "a beginners' group",
            "a change of kit supplier",
          ].join("\n"),
        },
      ],
    },
    {
      id: "t3-p2-match",
      type: "drag-text",
      part: 2,
      instructions:
        "Why did each of the following members join the club? Drag the correct answer from the box next to questions 15–18. You may use any answer more than once.",
      title: "Club members",
      text: [`Martin ${G}`, `Leah ${G}`, `Paul ${G}`, `Nadia ${G}`].join("\n\n"),
      options: ["to improve fitness", "to make friends", "to train for races"].join("\n"),
    },
    {
      id: "t3-p2-mcq",
      type: "mcq",
      variant: "single",
      part: 2,
      instructions: "Choose the correct letter, A, B or C.",
      questions: [
        {
          stem: "The club's annual dinner will be held",
          options: ["at a riverside hotel.", "in the clubhouse.", "at the sports centre."].join("\n"),
        },
        {
          stem: "Money raised at the dinner will pay for",
          options: ["new equipment.", "a youth programme.", "track hire."].join("\n"),
        },
      ],
    },
    {
      id: "t3-p3-mcq",
      type: "mcq",
      variant: "single",
      part: 3,
      instructions: "Choose the correct letter, A, B or C.",
      questions: [
        {
          stem: "Why did Dan and Mia choose to research the campus book-swap scheme?",
          options: [
            "It was recommended by a tutor.",
            "They had used it themselves.",
            "It was featured in the student newspaper.",
          ].join("\n"),
        },
        {
          stem: "They agree that the scheme's main problem is",
          options: ["a shortage of space.", "unreliable volunteers.", "a lack of publicity."].join("\n"),
        },
        {
          stem: "What surprised them about the users of the scheme?",
          options: ["their age range", "how far they travelled", "how many books they donated"].join("\n"),
        },
        {
          stem: "They decide that their questionnaire should be",
          options: ["short.", "anonymous.", "online only."].join("\n"),
        },
        {
          stem: "The tutor suggests they compare their findings with",
          options: ["a similar scheme abroad.", "a published study.", "an earlier student project."].join("\n"),
        },
      ],
    },
    {
      id: "t3-p3-match",
      type: "drag-text",
      part: 3,
      instructions:
        "Where in the new premises will each type of book be kept? Choose FIVE answers from the box and drag the correct answer next to questions 26–30.",
      title: "Types of book",
      text: [
        `Cookery books ${G}`,
        `Travel guides ${G}`,
        `Children's books ${G}`,
        `Textbooks ${G}`,
        `Rare books ${G}`,
      ].join("\n\n"),
      options: [
        "in the basement",
        "in the front window",
        "near the entrance",
        "on the first floor",
        "behind the counter",
        "in a locked cabinet",
        "in the storeroom",
      ].join("\n"),
    },
    {
      id: "t3-p4-notes",
      type: "pasted",
      part: 4,
      instructions: "Complete the notes below. Write ONE WORD ONLY for each answer.",
      text: [
        "The Greenhollow community woodland scheme",
        "Planting",
        "Trees are being planted on former 31_____ land.",
        "Native species cope better with local 32_____ than imported ones.",
        "Seeds are collected by 33_____ each autumn.",
        "Young trees are protected from 34_____ by plastic guards.",
        "Mixing different species reduces the spread of 35_____.",
        "The woodland in use",
        "Paths of 36_____ allow visitors to cross the wetter areas.",
        "Over time the woodland will store large amounts of 37_____.",
        "Dead wood is left on the ground as a habitat for 38_____.",
        "Local schools use the site for lessons in 39_____.",
        "The scheme's success will be measured by counting 40_____.",
      ].join("\n\n"),
    },
  ],
  answersRaw: [
    "side",
    "Garton",
    "9.15",
    "identification / ID",
    "pass",
    "canteen",
    "gym",
    "system",
    "20",
    "personnel",
    "A / E",
    "A / E",
    "A / D",
    "A / D",
    "to improve fitness",
    "to make friends",
    "to train for races",
    "to make friends",
    "A",
    "B",
    "B",
    "C",
    "A",
    "B",
    "C",
    "near the entrance",
    "on the first floor",
    "in the front window",
    "in the basement",
    "in a locked cabinet",
    "industrial",
    "pests",
    "volunteers",
    "rabbits / deer",
    "disease",
    "gravel",
    "carbon",
    "insects",
    "science",
    "birds",
  ].join("\n"),
};

// ============================================================================
// Template 4 — table · MCQ · map labelling · flowchart · notes
// ============================================================================

const TEMPLATE_4: AuthoredTest = {
  module: "listening",
  name: "Full Listening Test — Sample 4",
  status: "draft",
  startNumber: 1,
  groups: [
    {
      id: "t4-p1-table",
      type: "pasted",
      part: 1,
      instructions: "Complete the table below. Write ONE WORD AND/OR A NUMBER for each answer.",
      html: [
        "<p><b>Evening classes at Hartfield College</b></p>",
        "<table>",
        "<tbody>",
        "<tr><th>Class</th><th>Details</th><th>Cost</th></tr>",
        '<tr><td rowspan="2"><b>Photography</b></td><td>starts on 1_____</td><td rowspan="2">£ 2_____ per term</td></tr>',
        "<tr><td>students should bring their own 3_____</td></tr>",
        '<tr><td rowspan="2"><b>Cookery</b></td><td>held in the 4_____ building</td><td rowspan="2">fee includes all 5_____</td></tr>',
        "<tr><td>taught by a professional 6_____</td></tr>",
        '<tr><td rowspan="2"><b>Spanish</b></td><td>suitable for 7_____</td><td rowspan="2">limited to 8_____ people</td></tr>',
        "<tr><td>the course ends with a short 9_____</td></tr>",
        '<tr><td colspan="3"><i>Enrol in person at the 10_____ office.</i></td></tr>',
        "</tbody>",
        "</table>",
      ].join(""),
    },
    {
      id: "t4-p2-mcq",
      type: "mcq",
      variant: "single",
      part: 2,
      instructions: "Choose the correct letter, A, B or C.",
      questions: [
        {
          stem: "The main aim of the new town-centre traffic scheme is to",
          options: ["reduce accidents.", "cut journey times.", "improve air quality."].join("\n"),
        },
        {
          stem: "Most complaints about the current system concern",
          options: ["parking charges.", "bus delays.", "confusing signs."].join("\n"),
        },
        {
          stem: "The scheme will be reviewed after",
          options: ["six months.", "one year.", "two years."].join("\n"),
        },
      ],
    },
    {
      id: "t4-p2-map",
      type: "special",
      part: 2,
      instructions: "Label the map below. Write the correct letter, A–I, next to questions 14–20.",
      elements: { picture: true, table: true, drag: false, options: false },
      rows: [
        "14 New bus station",
        "15 Cycle hire point",
        "16 Pedestrian crossing",
        "17 Electric vehicle chargers",
        "18 Taxi rank",
        "19 Delivery bay",
        "20 Bicycle parking",
      ].join("\n"),
      cols: ["A", "B", "C", "D", "E", "F", "G", "H", "I"].join("\n"),
    },
    {
      id: "t4-p3-mcq",
      type: "mcq",
      variant: "single",
      part: 3,
      instructions: "Choose the correct letter, A, B or C.",
      questions: [
        {
          stem: "Why did Priya choose bean seeds for the experiment?",
          options: ["They germinate quickly.", "They were easy to obtain.", "They are large enough to measure."].join("\n"),
        },
        {
          stem: "The students decide to control the temperature by using",
          options: ["a heated cupboard.", "a laboratory incubator.", "a sunny windowsill."].join("\n"),
        },
        {
          stem: "What mistake did the students make in their first trial?",
          options: ["They overwatered the seeds.", "They used the wrong soil.", "They mislabelled the trays."].join("\n"),
        },
        {
          stem: "James thinks their results may be affected by",
          options: ["the age of the seeds.", "the level of light.", "the quality of the water."].join("\n"),
        },
        {
          stem: "The tutor advises them to present their results in",
          options: ["a table.", "a line graph.", "a series of photographs."].join("\n"),
        },
      ],
    },
    {
      id: "t4-p3-flow",
      type: "flowchart",
      part: 3,
      instructions:
        "Complete the flowchart below. Choose FIVE answers from the box and drag the correct answer into questions 26–30.",
      title: "Preparing the seed trays",
      steps: [
        `Wash the trays and attach ${G} to each one.`,
        `Fill the trays with equal amounts of ${G}.`,
        `Plant the seeds at the same ${G}.`,
        `Add a measured volume of ${G}.`,
        `Check daily and record changes on ${G}.`,
      ],
      options: [
        "a label",
        "compost",
        "depth",
        "water",
        "the record sheet",
        "a lid",
        "a ruler",
        "a thermometer",
      ].join("\n"),
    },
    {
      id: "t4-p4-notes",
      type: "pasted",
      part: 4,
      instructions: "Complete the notes below. Write ONE WORD ONLY for each answer.",
      text: [
        "How foxes have adapted to city life",
        "Behaviour",
        "City foxes have much smaller territories than foxes in the 31_____.",
        "They are mainly active at 32_____.",
        "Their diet includes a surprising amount of 33_____.",
        "They remember the locations of reliable sources of 34_____.",
        "Urban foxes are far less afraid of 35_____ than rural foxes are.",
        "Research methods",
        "Recent studies used tiny 36_____ attached to collars.",
        "Cubs are usually born under garden 37_____.",
        "The greatest danger to urban foxes is 38_____.",
        "Food left out by residents can cause 39_____ between neighbouring foxes.",
        "The public can report sightings on the project's 40_____.",
      ].join("\n\n"),
    },
  ],
  answersRaw: [
    "Tuesday",
    "65",
    "tripod",
    "Newton",
    "ingredients",
    "chef",
    "beginners",
    "12 / twelve",
    "test",
    "admissions",
    "C",
    "B",
    "A",
    "C",
    "A",
    "F",
    "I",
    "D",
    "G",
    "B",
    "A",
    "B",
    "C",
    "A",
    "B",
    "a label",
    "compost",
    "depth",
    "water",
    "the record sheet",
    "countryside",
    "night",
    "fruit",
    "food",
    "people",
    "cameras",
    "sheds",
    "traffic",
    "fights",
    "website",
  ].join("\n"),
};

// ============================================================================
// Template 5 — table · diagram labelling · matching · short answers · MCQ
// ============================================================================

const TEMPLATE_5: AuthoredTest = {
  module: "listening",
  name: "Full Listening Test — Sample 5",
  status: "draft",
  startNumber: 1,
  groups: [
    {
      id: "t5-p1-table",
      type: "pasted",
      part: 1,
      instructions: "Complete the table below. Write ONE WORD ONLY for each answer.",
      html: [
        '<table><tbody>',
        '<tr><th colspan="2">Riverside Dental Practice — new patient information</th></tr>',
        '<tr><td rowspan="2"><b>Dentists</b></td><td>Dr 1_____ specialises in treating children</td></tr>',
        "<tr><td>Dr Gray runs a clinic for patients with 2_____ problems</td></tr>",
        "<tr><td><b>Registration</b></td><td>bring a completed 3_____ form</td></tr>",
        "<tr><td><b>Hygienist</b></td><td>gives advice on 4_____</td></tr>",
        '<tr><td rowspan="2"><b>Appointments</b></td><td>can be cancelled by 5_____</td></tr>',
        "<tr><td>an emergency 6_____ service is available at weekends</td></tr>",
        '<tr><td rowspan="2"><b>Access</b></td><td>parking is available behind the 7_____</td></tr>',
        "<tr><td>wheelchair users should use the 8_____ entrance</td></tr>",
        "<tr><td><b>Families</b></td><td>the waiting room has a play area for 9_____</td></tr>",
        "<tr><td><b>Payment</b></td><td>monthly payment 10_____ are available for regular patients</td></tr>",
        "</tbody></table>",
      ].join(""),
    },
    {
      id: "t5-p2-diagram",
      type: "special",
      part: 2,
      instructions: "Label the plan of the holiday cottage. Write the correct letter, A–E, next to questions 11–13.",
      elements: { picture: true, table: true, drag: false, options: false },
      rows: ["11 Storage cupboard", "12 Heating controls", "13 Spare keys"].join("\n"),
      cols: ["A", "B", "C", "D", "E"].join("\n"),
    },
    {
      id: "t5-p2-match",
      type: "drag-text",
      part: 2,
      instructions:
        "Where can guests find each of the following? Choose FIVE answers from the box and drag the correct answer next to questions 14–18.",
      title: "Items in the cottage",
      text: [
        `Barbecue equipment ${G}`,
        `Extra blankets ${G}`,
        `Board games ${G}`,
        `Garden chairs ${G}`,
        `Local maps ${G}`,
      ].join("\n\n"),
      options: [
        "in the garage",
        "under the stairs",
        "in the hall cupboard",
        "in the main bedroom",
        "on the bookshelf",
        "in the garden shed",
        "at the neighbour's house",
      ].join("\n"),
    },
    {
      id: "t5-p2-notes",
      type: "pasted",
      part: 2,
      instructions: "Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.",
      text: ["The nearest shop is 19_____ km away.", "If there is a problem, ring the owner on 20_____."].join("\n\n"),
    },
    {
      id: "t5-p3-mcq",
      type: "mcq",
      variant: "single",
      part: 3,
      instructions: "Choose the correct letter, A, B or C.",
      questions: [
        {
          stem: "Elena says the hardest part of her first term abroad was",
          options: ["understanding lectures.", "making friends.", "finding accommodation."].join("\n"),
        },
        {
          stem: "What helped her most to improve her language?",
          options: ["extra classes", "a part-time job", "watching local television"].join("\n"),
        },
      ],
    },
    {
      id: "t5-p3-sentences",
      type: "pasted",
      part: 3,
      instructions: "Complete the sentences below. Write ONE WORD ONLY for each answer.",
      text: [
        "Joining the university 23_____ club helped Elena meet local students.",
        "She had to write far more 24_____ than at her home university.",
        "Her favourite course included a group 25_____.",
      ].join("\n\n"),
    },
    {
      id: "t5-p3-short",
      type: "pasted",
      part: 3,
      instructions:
        "Answer the questions below. Write NO MORE THAN THREE WORDS AND/OR A NUMBER for each answer.",
      text: [
        "What does Elena plan to study next year? 26_____",
        "Who paid for her travel costs? 27_____",
        "How long did her student visa take to arrive? 28_____",
        "What does she advise new exchange students to take with them? 29_____",
        "What will she miss most about the city? 30_____",
      ].join("\n\n"),
    },
    {
      id: "t5-p4-mcq",
      type: "mcq",
      variant: "single",
      part: 4,
      instructions: "Choose the correct letter, A, B or C.",
      questions: [
        {
          stem: "The garden wildlife survey was started in order to",
          options: [
            "track a decline in bird numbers.",
            "compare gardens with public parks.",
            "test a new counting method.",
          ].join("\n"),
        },
        {
          stem: "Most of the data was collected by",
          options: ["university students.", "professional ecologists.", "ordinary householders."].join("\n"),
        },
        {
          stem: "Participants were most likely to give up when",
          options: ["the weather was poor.", "the paperwork increased.", "their gardens changed."].join("\n"),
        },
        {
          stem: "The biggest surprise in the results concerned",
          options: ["hedgehogs.", "frogs.", "bats."].join("\n"),
        },
        {
          stem: "Small ponds proved more valuable than expected because",
          options: ["they warm up quickly.", "they rarely contain fish.", "they attract insects."].join("\n"),
        },
        {
          stem: "The researchers now want to study the effect of",
          options: ["garden lighting.", "fences and walls.", "lawn care."].join("\n"),
        },
      ],
    },
    {
      id: "t5-p4-table",
      type: "pasted",
      part: 4,
      instructions: "Complete the table below. Write ONE WORD ONLY for each answer.",
      html: [
        "<table><tbody>",
        '<tr><th colspan="2">Recommendations for wildlife-friendly gardens</th></tr>',
        "<tr><th>Shelter</th><td>leave a pile of 37_____ in a corner</td></tr>",
        "<tr><th>Planting</th><td>grow flowers that are rich in 38_____</td></tr>",
        "<tr><th>Boundaries</th><td>make a small 39_____ in the bottom of each fence</td></tr>",
        "<tr><th>Maintenance</th><td>avoid using chemical 40_____</td></tr>",
        "</tbody></table>",
      ].join(""),
    },
  ],
  answersRaw: [
    "Fuller",
    "gum",
    "registration",
    "diet",
    "text",
    "telephone",
    "library",
    "rear",
    "children",
    "plans",
    "B",
    "D",
    "A",
    "in the garage",
    "in the main bedroom",
    "on the bookshelf",
    "in the garden shed",
    "in the hall cupboard",
    "2 / two",
    "01632 960128",
    "A",
    "B",
    "climbing",
    "essays",
    "project",
    "European law / law",
    "her university / the university",
    "6 weeks / six weeks",
    "photographs / family photographs",
    "the markets / markets",
    "A",
    "C",
    "B",
    "A",
    "B",
    "B",
    "logs",
    "nectar",
    "hole / gap",
    "pesticides",
  ].join("\n"),
};

export const LISTENING_TEMPLATES: ListeningTemplate[] = [
  { id: "sample-1", label: "Sample 1 — notes · MCQ · matching · choose TWO", test: TEMPLATE_1 },
  { id: "sample-2", label: "Sample 2 — notes · map labelling · choose TWO · matching", test: TEMPLATE_2 },
  { id: "sample-3", label: "Sample 3 — choose TWO · matching ×2 · MCQ · notes", test: TEMPLATE_3 },
  { id: "sample-4", label: "Sample 4 — table · map labelling · flowchart · notes", test: TEMPLATE_4 },
  { id: "sample-5", label: "Sample 5 — table · diagram · short answers · MCQ", test: TEMPLATE_5 },
];
