// A library of complete 40-question reading tests (3 passages each) the
// teacher can load into the question builder and edit freely. Each template
// mirrors the structure of a real academic reading paper — part layout,
// question types, instruction formats — with original sample passages and
// questions the teacher replaces with their own material.

import type { AuthoredTest } from "./authoring";
import { GAP_TOKEN } from "./authoring";
import type { ListeningTemplate } from "./listening-template";

const G = GAP_TOKEN;

export type ReadingTemplate = ListeningTemplate;

const P = (...paras: string[]) => paras.join("\n\n");

// ============================================================================
// Sample 1 — TFNG · completion · matching info · choose TWO · summary ·
//            MCQ · summary from box · YNNG
// ============================================================================

const READING_1: AuthoredTest = {
  module: "reading",
  name: "Full Reading Test — Sample 1",
  status: "draft",
  startNumber: 1,
  readingPassages: [
    {
      title: "The evolution of the racing bicycle",
      passage: P(
        "The first machines that could reasonably be called bicycles appeared in Europe in the middle of the nineteenth century. They were heavy, uncomfortable and difficult to steer, and their wooden wheels transmitted every bump in the road directly to the rider. Even so, they quickly became popular with young men in cities, and informal races were soon being held on park paths and country roads.",
        "The introduction of the metal-spoked wheel and the air-filled rubber tyre in the 1880s transformed the machine. For the first time, a bicycle could be both light and comfortable, and manufacturers began to compete seriously over the weight of their frames. By the end of the century, racing models weighed less than half as much as the machines of twenty years earlier.",
        "Racing itself shaped the technology. Long road races demanded machines that could be repaired quickly, so parts were standardised, while track racing encouraged experiments with unusual frame shapes designed to cut through the air. Many features now found on ordinary city bicycles, including the lightweight frame and the multi-speed gear, were first developed for competition.",
        "The greatest change of the twentieth century was the arrival of new materials. Steel gave way to aluminium, and aluminium in turn to carbon fibre, a material that could be moulded into almost any shape. Designers were no longer limited by the straight tubes of a traditional frame, and the machines of the 1990s looked radically different from anything that had come before.",
        "Modern racing bicycles are now so advanced that the sport's governing body imposes strict limits on their design, including a minimum weight. Manufacturers respond by improving areas the rules do not cover, such as the smoothness of the bearings and the precision of the gears. The bicycle, one of the simplest machines ever invented, continues to be refined more than a century and a half after its birth.",
      ),
    },
    {
      title: "The lighthouse keepers of Aldwick Rock",
      passage: P(
        "A  Twenty kilometres off the south-west coast lies Aldwick Rock, a ridge of granite that is covered by the sea at high tide. For centuries it wrecked ships with such regularity that sailors called it the Graveyard, and by the eighteenth century the demand for a permanent light on the rock had become impossible to ignore.",
        "B  The first tower, completed in 1761, was built of timber and lasted barely a decade before a winter storm swept it away. Its replacement, designed by the engineer Samuel Croft, was made of interlocking granite blocks cut so precisely that no mortar was needed. Croft's tower stood for more than a hundred years and became the model for wave-swept lighthouses around the world.",
        "C  Life on the rock was hard. Three keepers lived in the tower at any one time, working in shifts to keep the oil lamps burning from dusk until dawn. Supplies arrived by boat once a month, weather permitting, and in a bad winter the keepers could be cut off for six weeks or more.",
        "D  The keepers developed remarkable skills. They could forecast the weather from the behaviour of seabirds, repair almost any piece of equipment with the tools at hand, and communicate with passing ships using flags and lamps. Several kept detailed diaries which are now valued by historians as records of weather and shipping.",
        "E  The tower was electrified in 1952, which ended the nightly routine of trimming wicks and winding clockwork. Even so, keepers remained essential: the machinery needed constant maintenance, and in fog the great horn had to be sounded by hand every ninety seconds.",
        "F  Automation finally arrived in 1988. The last three keepers left the rock in November of that year, and the light has been controlled from the mainland ever since. Sensors now report on everything from the state of the batteries to the humidity inside the lamp room.",
        "G  Today the tower is maintained by a small team who visit by helicopter four times a year. There are proposals to open the building to visitors during the summer months, though the difficulty of landing on the rock means that most admirers will continue to see it only from the deck of a passing boat.",
      ),
    },
    {
      title: "Why we misremember",
      passage: P(
        "Most people think of memory as a recording device: events are stored when they happen and played back when needed. Decades of research have shown that this picture is wrong. Remembering is an act of reconstruction, in which the brain rebuilds an event from fragments, filling any gaps with guesses so smoothly that we rarely notice the joins.",
        "In a well-known series of experiments, volunteers watched a film of a minor traffic accident and were later asked how fast the cars were travelling. Those asked how fast the cars were going when they 'smashed into' each other gave much higher estimates than those asked about cars that 'contacted' each other, and a week later many of the first group remembered seeing broken glass where there was none. A single word in a question had rewritten their memory of the event.",
        "This malleability has serious consequences in the courtroom. Witnesses who repeat their story many times become steadily more confident, but no more accurate, and jurors consistently mistake confidence for reliability. Several legal systems have responded by changing the way identification evidence is collected, insisting, for example, that a witness's certainty be recorded at the moment of the first identification and not after.",
        "Why would evolution give us such an unreliable instrument? Many researchers argue that memory is not designed to archive the past at all, but to help us predict the future. A system that stores the general pattern of events, rather than every detail, is faster and more flexible, and the same machinery that reconstructs the past allows us to imagine situations we have never experienced.",
        "Seen this way, our errors are not flaws but by-products of a system doing something more useful than recording. The challenge, in courtrooms and classrooms alike, is to build practices that work with the grain of reconstruction rather than pretending we each carry a perfect archive behind our eyes.",
      ),
    },
  ],
  groups: [
    {
      id: "r1-p1-tfng",
      type: "mcq",
      variant: "tfng",
      part: 1,
      instructions:
        "Do the following statements agree with the information given in the passage? Write TRUE, FALSE or NOT GIVEN.",
      questions: [
        { stem: "Early bicycles were popular despite being uncomfortable to ride.", options: "" },
        { stem: "Informal bicycle races were banned in most European cities.", options: "" },
        { stem: "The air-filled tyre was invented before the metal-spoked wheel.", options: "" },
        { stem: "By 1900, racing bicycles were much lighter than those of the 1880s.", options: "" },
        { stem: "The multi-speed gear was first developed for everyday city bicycles.", options: "" },
        { stem: "Carbon fibre allowed designers to move away from traditional frame shapes.", options: "" },
        { stem: "The sport's governing body sets a minimum weight for racing bicycles.", options: "" },
      ],
    },
    {
      id: "r1-p1-completion",
      type: "pasted",
      part: 1,
      instructions: "Complete the sentences below. Write ONE WORD ONLY from the passage for each answer.",
      text: P(
        "The wheels of the earliest bicycles were made of 8_____.",
        "In the 1880s, manufacturers began competing over the 9_____ of their frames.",
        "Parts were standardised so that machines could be 10_____ quickly during long races.",
        "Track racing led to frame shapes designed to cut through the 11_____.",
        "During the twentieth century, steel was first replaced by 12_____.",
        "Modern manufacturers work on improving the 13_____ of the bearings.",
      ),
    },
    {
      id: "r1-p2-matchinfo",
      type: "table",
      part: 2,
      instructions:
        "The passage has seven paragraphs, A–G. Which paragraph contains the following information? Select the correct letter, A–G.",
      rows: [
        "a description of how the keepers stayed in contact with ships",
        "a reason why a light was needed on the rock",
        "the failure of the first tower",
        "a change that removed a nightly task",
        "how the tower is looked after nowadays",
        "the length of time keepers could be isolated",
      ].join("\n"),
      cols: "A\nB\nC\nD\nE\nF\nG",
    },
    {
      id: "r1-p2-double",
      type: "mcq",
      variant: "double",
      part: 2,
      instructions: "Choose TWO letters, A–E.",
      questions: [
        {
          stem: "Which TWO facts are given about Samuel Croft's tower?",
          options: [
            "It was built without mortar.",
            "It was the tallest lighthouse of its time.",
            "It influenced lighthouse design elsewhere.",
            "It was destroyed in a storm.",
            "It took ten years to build.",
          ].join("\n"),
        },
        {
          stem: "Which TWO skills of the keepers are mentioned in the passage?",
          options: [
            "predicting the weather",
            "catching fish in rough seas",
            "repairing equipment",
            "building small boats",
            "training new recruits",
          ].join("\n"),
        },
      ],
    },
    {
      id: "r1-p2-summary",
      type: "pasted",
      part: 2,
      instructions: "Complete the summary below. Write ONE WORD ONLY from the passage for each answer.",
      title: "The end of the keepers",
      text: P(
        "The tower was electrified in 1952, but keepers were still needed to maintain the machinery and, in fog, to sound the 24_____ by hand. The station was finally automated in 1988, and the light is now controlled from the 25_____. Maintenance visits are made four times a year by 26_____.",
      ),
    },
    {
      id: "r1-p3-mcq",
      type: "mcq",
      variant: "single",
      part: 3,
      instructions: "Choose the correct letter, A, B, C or D.",
      questions: [
        {
          stem: "According to the writer, most people wrongly believe that memory",
          options: [
            "works like a recording device.",
            "improves with regular practice.",
            "is more accurate in childhood.",
            "cannot be studied scientifically.",
          ].join("\n"),
        },
        {
          stem: "The traffic accident experiments showed that",
          options: [
            "witnesses rarely agree about speed.",
            "the wording of a question can change a memory.",
            "people forget accidents very quickly.",
            "films are a poor way to test memory.",
          ].join("\n"),
        },
        {
          stem: "What does the writer say about confident witnesses?",
          options: [
            "They are usually more accurate.",
            "They are trusted too readily by jurors.",
            "They change their stories more often.",
            "They are rarely called to court.",
          ].join("\n"),
        },
        {
          stem: "Some legal systems now require that a witness's certainty is",
          options: [
            "assessed by a psychologist.",
            "ignored by the jury.",
            "recorded at the first identification.",
            "tested with a second identification.",
          ].join("\n"),
        },
      ],
    },
    {
      id: "r1-p3-summarybox",
      type: "drag-text",
      part: 3,
      instructions:
        "Complete the summary using the list of words, A–J, below. Drag the correct word into each gap.",
      title: "Memory as prediction",
      text: P(
        `Many researchers now argue that memory did not evolve to ${G} the past.`,
        `Instead, its purpose is to help us ${G} the future.`,
        `Storing the general ${G} of events makes the system faster.`,
        `The same machinery lets us ${G} situations we have never met.`,
        `Our memory errors are therefore best seen as ${G} of a useful design.`,
        `Practices in courtrooms should work with the grain of ${G}.`,
      ),
      options: [
        "archive",
        "predict",
        "pattern",
        "imagine",
        "by-products",
        "reconstruction",
        "confidence",
        "detail",
        "flaws",
        "evidence",
      ].join("\n"),
    },
    {
      id: "r1-p3-ynng",
      type: "mcq",
      variant: "ynng",
      part: 3,
      instructions:
        "Do the following statements agree with the claims of the writer? Write YES, NO or NOT GIVEN.",
      questions: [
        { stem: "Remembering involves rebuilding events from fragments.", options: "" },
        { stem: "Repeating a story makes a witness's account more accurate.", options: "" },
        { stem: "Children's memories are more reliable than adults' memories.", options: "" },
        { stem: "Memory errors can be seen as the price of a flexible system.", options: "" },
      ],
    },
  ],
  answersRaw: [
    "TRUE",
    "NOT GIVEN",
    "FALSE",
    "TRUE",
    "FALSE",
    "TRUE",
    "TRUE",
    "wood / wooden",
    "weight",
    "repaired",
    "air",
    "aluminium / aluminum",
    "smoothness",
    "D",
    "A",
    "B",
    "E",
    "G",
    "C",
    "A / C",
    "A / C",
    "A / C",
    "A / C",
    "horn",
    "mainland",
    "helicopter",
    "A",
    "B",
    "B",
    "C",
    "archive",
    "predict",
    "pattern",
    "imagine",
    "by-products",
    "reconstruction",
    "YES",
    "NO",
    "NOT GIVEN",
    "YES",
  ].join("\n"),
};

// ============================================================================
// Sample 2 — TFNG · notes · matching info · sentence completion ·
//            matching people · MCQ · sentence endings · YNNG
// ============================================================================

const READING_2: AuthoredTest = {
  module: "reading",
  name: "Full Reading Test — Sample 2",
  status: "draft",
  startNumber: 1,
  readingPassages: [
    {
      title: "The first farmers of the high valleys",
      passage: P(
        "Archaeologists long assumed that farming spread into mountainous regions late, carried by settlers from the lowland plains. Recent excavations in the high valleys of central Asia are overturning that view. At sites more than two thousand metres above sea level, researchers have found carbonised grains of wheat and barley that are nearly five thousand years old.",
        "The grains tell a subtle story. Barley from the highest sites shows changes in its structure associated with tolerance of cold and a short growing season, evidence that the crop was not simply imported each year but was being grown, selected and adapted on the spot by the villagers themselves.",
        "The villages were small, rarely more than a dozen houses, built of stone and timber on terraces above the valley floor. Their inhabitants kept goats and a few cattle, hunted in the forests, and traded with travellers moving between the lowlands on either side of the range. Beads of marine shell, found far from any sea, show how long these exchange routes were.",
        "Why farm in such a hard place at all? One suggestion is that the valleys were not marginal at all but attractive: reliable streams of meltwater made harvests more dependable than on the drought-prone plains below. The mountain communities may have been not stragglers at the edge of the farming world, but pioneers who solved problems the lowlands had yet to face.",
        "Work at these sites is slow, since the digging season lasts only three months before the snow returns. But each summer adds detail to a picture of early mountain life that is proving far richer, and far more inventive, than anyone expected a generation ago.",
      ),
    },
    {
      title: "Bringing city rivers back to life",
      passage: P(
        "A  For most of the industrial era, city rivers were treated as drains. They carried away waste, they flooded, and eventually many of them were simply buried, entombed in brick culverts beneath streets and car parks. A city could forget it had a river at all.",
        "B  Attitudes began to change in the late twentieth century, as heavy industry left city centres and the worst pollution eased. Planners rediscovered what older cities had always known: that people are drawn to water, and that a clean riverbank raises the value of everything around it.",
        "C  The boldest projects now go beyond cleaning and actually dig rivers up again. Daylighting, as the process is known, involves removing the culvert and recreating an open channel, complete with planted banks and paths. The engineering is delicate, since the buried river often runs beneath buildings and roads that cannot be moved.",
        "D  The ecological rewards can be startling. Within two years of one daylighting scheme, surveys recorded fish in a stretch of water that had flowed through a concrete pipe for ninety years. Insects, birds and even otters followed. An open river, it turns out, restocks itself with remarkable speed.",
        "E  There are social rewards too. Streets facing restored rivers report more pedestrians, more small businesses and cooler summer temperatures. In one district, hospital admissions for heat-related illness fell measurably after a river and its trees replaced a four-lane road.",
        "F  Critics point to the cost, which can exceed that of a conventional park by several times, and warn that rising property values can push out the very residents the schemes were meant to serve. Some cities now pair river restoration with protected housing to address exactly this risk.",
        "G  Flooding remains the hardest argument. A buried river in a pipe has a fixed capacity; an open river with wide, planted banks can swell safely during storms. As rainfall becomes more intense, engineers increasingly see daylighting not as a luxury but as infrastructure.",
        "H  The movement is young, and no one claims that every buried stream can or should be uncovered. But the successes have changed the question cities ask. It is no longer whether they can afford to bring their rivers back, but whether they can afford not to.",
      ),
    },
    {
      title: "Instant speech translation",
      passage: P(
        "Devices that promise to translate speech as it is spoken have moved in a decade from science fiction to the pockets of tourists. A traveller can now speak into a phone and hear their words repeated, a second or two later, in a language they have never studied. The technology behind this apparent magic is a chain of three systems: one that turns speech into text, one that translates the text, and one that turns the translation back into speech.",
        "Each link in the chain has been transformed by machine learning. Rather than being programmed with rules of grammar, modern systems are trained on enormous collections of translated sentences, from which they learn patterns no engineer ever wrote down. The results outstrip the rule-based systems of the past, but they inherit a weakness: the machine has no understanding of what the words mean, only of how they tend to behave.",
        "This shows in predictable ways. The systems handle common, concrete sentences well, and struggle with jokes, idioms and anything that depends on context spread across a conversation. They can also fail unevenly across languages: a system trained mostly on European languages may perform poorly on languages with fewer digital texts, a problem researchers call the data gap.",
        "Professional interpreters watch the technology with mixed feelings. Many use it themselves for routine preparation, and most agree that it has made simple exchanges easier for millions of people. But they argue that high-stakes settings, such as courtrooms, hospitals and diplomatic negotiations, involve far more than converting words, and that the profession's future lies precisely where the machines are weakest.",
        "The next decade will test that claim. Systems are beginning to listen to whole conversations rather than single sentences, and to preserve the speaker's tone of voice in the translated output. Whether that amounts to understanding, or only to a more convincing imitation of it, is a question the machines themselves cannot answer.",
      ),
    },
  ],
  groups: [
    {
      id: "r2-p1-tfng",
      type: "mcq",
      variant: "tfng",
      part: 1,
      instructions:
        "Do the following statements agree with the information given in the passage? Write TRUE, FALSE or NOT GIVEN.",
      questions: [
        { stem: "Archaeologists once believed farming reached mountain regions late.", options: "" },
        { stem: "The grains found at the high sites are around five thousand years old.", options: "" },
        { stem: "Barley grown at the highest sites showed signs of adaptation to cold.", options: "" },
        { stem: "The mountain villages each contained several hundred houses.", options: "" },
        { stem: "Marine shells were found at the mountain sites.", options: "" },
        { stem: "The digging season at the sites lasts for six months.", options: "" },
        { stem: "The researchers plan to publish their findings next year.", options: "" },
      ],
    },
    {
      id: "r2-p1-notes",
      type: "pasted",
      part: 1,
      instructions: "Complete the notes below. Write ONE WORD ONLY from the passage for each answer.",
      title: "Life in the high valleys",
      text: P(
        "Houses: built of stone and 8_____ on terraces",
        "Animals kept: goats and some 9_____",
        "Contact with outside: trade with 10_____ crossing the range",
        "Advantage of the valleys: streams of 11_____ made harvests dependable",
        "The villagers may have been 12_____ rather than stragglers",
        "Fieldwork ends each year when the 13_____ returns",
      ),
    },
    {
      id: "r2-p2-matchinfo",
      type: "table",
      part: 2,
      instructions:
        "The passage has eight paragraphs, A–H. Which paragraph contains the following information? Select the correct letter, A–H.",
      rows: [
        "a health benefit recorded after a restoration scheme",
        "why daylighting engineering must be done carefully",
        "a description of how cities once treated their rivers",
        "a way of preventing residents from being displaced",
      ].join("\n"),
      cols: "A\nB\nC\nD\nE\nF\nG\nH",
    },
    {
      id: "r2-p2-sentences",
      type: "pasted",
      part: 2,
      instructions: "Complete the sentences below. Write ONE WORD ONLY from the passage for each answer.",
      text: P(
        "Many buried rivers were enclosed in brick 18_____ under the streets.",
        "Fish returned to one restored river within two 19_____ of the scheme.",
        "Restored riverbanks attract pedestrians and small 20_____.",
        "Daylighting can cost several times more than a conventional 21_____.",
        "Wide, planted banks let a river swell safely during 22_____.",
      ),
    },
    {
      id: "r2-p2-people",
      type: "table",
      part: 2,
      instructions:
        "Look at the following statements and the list of researchers: A — Prof. Lena Odum; B — Dr Marcus Bell; C — Dr Sofia Reyes; D — Prof. Theo Kessler. Match each statement with the correct researcher, A–D.",
      rows: [
        "Daylighting should be classed as flood infrastructure.",
        "Restored rivers recover their wildlife faster than predicted.",
        "The cost of schemes is often underestimated by councils.",
        "River projects must be paired with protected housing.",
      ].join("\n"),
      cols: "A\nB\nC\nD",
    },
    {
      id: "r2-p3-mcq",
      type: "mcq",
      variant: "single",
      part: 3,
      instructions: "Choose the correct letter, A, B, C or D.",
      questions: [
        {
          stem: "The writer describes instant translation as a chain of",
          options: ["two systems.", "three systems.", "four systems.", "five systems."].join("\n"),
        },
        {
          stem: "Modern translation systems learn from",
          options: [
            "rules written by engineers.",
            "recordings of interpreters.",
            "large collections of translated sentences.",
            "dictionaries of idioms.",
          ].join("\n"),
        },
        {
          stem: "The 'data gap' refers to",
          options: [
            "the delay between speech and translation.",
            "the shortage of digital texts in some languages.",
            "the cost of training new systems.",
            "the difference between speech and writing.",
          ].join("\n"),
        },
        {
          stem: "According to the writer, professional interpreters believe their future lies in",
          options: [
            "routine tourist exchanges.",
            "building better machines.",
            "settings where machines are weakest.",
            "teaching languages.",
          ].join("\n"),
        },
      ],
    },
    {
      id: "r2-p3-endings",
      type: "drag-text",
      part: 3,
      instructions: "Complete each sentence with the correct ending, A–F, below. Drag the correct ending into each gap.",
      text: P(
        `Machine translation systems handle concrete, common sentences ${G}`,
        `Jokes and idioms cause the systems ${G}`,
        `Many interpreters use the technology ${G}`,
        `Newer systems attempt to preserve ${G}`,
      ),
      options: [
        "well.",
        "serious difficulty.",
        "for routine preparation.",
        "the speaker's tone of voice.",
        "without any training data.",
        "only in European languages.",
      ].join("\n"),
    },
    {
      id: "r2-p3-ynng",
      type: "mcq",
      variant: "ynng",
      part: 3,
      instructions:
        "Do the following statements agree with the claims of the writer? Write YES, NO or NOT GIVEN.",
      questions: [
        { stem: "Modern systems understand the meaning of the words they translate.", options: "" },
        { stem: "Instant translation has made simple exchanges easier for many people.", options: "" },
        { stem: "Interpreters should be replaced in hospitals within a decade.", options: "" },
        { stem: "Courtroom interpreting involves more than converting words.", options: "" },
        { stem: "Most tourists prefer human interpreters to devices.", options: "" },
        { stem: "Future systems will analyse whole conversations.", options: "" },
      ],
    },
  ],
  answersRaw: [
    "TRUE",
    "TRUE",
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    "NOT GIVEN",
    "timber",
    "cattle",
    "travellers / travelers",
    "meltwater",
    "pioneers",
    "snow",
    "E",
    "C",
    "A",
    "F",
    "culverts",
    "years",
    "businesses",
    "park",
    "storms",
    "D",
    "B",
    "C",
    "A",
    "B",
    "C",
    "B",
    "C",
    "well.",
    "serious difficulty.",
    "for routine preparation.",
    "the speaker's tone of voice.",
    "NO",
    "YES",
    "NOT GIVEN",
    "YES",
    "NOT GIVEN",
    "YES",
  ].join("\n"),
};

// ============================================================================
// Sample 3 — TFNG · completion · matching headings · summary ·
//            sentence endings · summary from box · MCQ
// ============================================================================

const READING_3: AuthoredTest = {
  module: "reading",
  name: "Full Reading Test — Sample 3",
  status: "draft",
  startNumber: 1,
  readingPassages: [
    {
      title: "The potter Ellen Marsh",
      passage: P(
        "Ellen Marsh was born in 1902 in a small town whose economy rested on its brickworks. Clay was everywhere: in the fields, in the riverbanks, and in the pockets of every child who played there. Marsh later said that she could not remember a time before she modelled things with her hands.",
        "Her formal training was brief. At seventeen she won a scholarship to an art school in the capital, but she left after two years, impatient with a curriculum that treated pottery as a minor craft beneath the attention of serious artists. She set up her first workshop in a disused stable, firing her work in a kiln she built herself from salvaged brick.",
        "Recognition came slowly. Her early pots, with their thick walls and muted colours, were dismissed by critics used to fine porcelain. It was a department store, not a gallery, that gave her a first commercial break, ordering two hundred plain tableware sets that sold out within a month.",
        "The turning point in her artistic reputation came with the exhibition of 1934, in which she showed a series of large vessels glazed in a deep copper red she had spent six years perfecting. The colour, produced by starving the kiln of oxygen at a precise moment, was so difficult to control that fewer than one firing in five succeeded. Collectors who had ignored her now competed for her work.",
        "Marsh spent her later years teaching, insisting that her students master materials before style. She died in 1978, leaving her workshop and its contents to the town museum, where her kiln, still black from its last firing, remains the most visited exhibit.",
      ),
    },
    {
      title: "A solar water purifier",
      passage: P(
        "Around the world, hundreds of millions of people lack reliable access to safe drinking water, and many of them live in places with abundant sunshine. That coincidence is the starting point for a device developed by a small engineering team: a portable purifier that uses sunlight alone to turn contaminated or salty water into drinking water.",
        "The device resembles a slim suitcase. Unfolded, it presents a dark absorbing surface beneath a transparent cover. Water drawn from any source flows in a thin film across the absorber, where sunlight heats it and part of it evaporates, leaving salts, microbes and sediment behind. The vapour condenses on the cool underside of the cover and trickles into a clean reservoir.",
        "Earlier solar stills worked on the same principle but produced discouragingly little water. The team's main advance is a stack of evaporating layers that reuses the heat released each time vapour condenses, instead of letting it escape. Each layer squeezes another round of evaporation from the same sunlight, multiplying the output several times over.",
        "Field trials were run in three coastal villages over two years. Families reported that the device produced enough water for drinking and cooking on all but the cloudiest days, and testing showed that the output met international drinking standards. The most common complaint concerned not the water but the slow accumulation of salt crust, which must be rinsed away weekly.",
        "The price remains the largest obstacle. At roughly the cost of a bicycle, the device is cheap by the standards of water infrastructure but expensive for the poorest households, and the team is experimenting with a lease model in which a village co-operative owns a shared fleet.",
        "Aid agencies are also interested in a different use: emergencies. Because the device needs no fuel, no spare parts and no operator training, it can be dropped into a flood or earthquake zone and produce safe water within an hour of being unfolded.",
        "The designers are careful not to oversell their work. A device that makes a few litres a day will not solve a city's water crisis, they point out; that requires pipes, treatment plants and political will. What it can do is bridge the gap for the household, the clinic or the school that the pipes have not yet reached.",
      ),
    },
    {
      title: "Why stories survive",
      passage: P(
        "Every human culture tells stories, and many of the stories are strikingly alike. Tales of floods, of clever animals, of the poor child who triumphs, appear on every continent, often in societies with no known contact. For scholars of culture, this similarity is a puzzle demanding explanation.",
        "One approach borrows its tools from evolutionary biology. Stories, in this view, are like organisms: they are copied each time they are retold, they vary in the copying, and they compete for the limited attention and memory of human minds. The tales that survive centuries of retelling are the ones best adapted to being remembered and repeated.",
        "Laboratory work supports the idea. In experiments where a story is passed along a chain of readers, each retelling from memory, the tale shrinks and changes in consistent ways. Details that carry no consequence disappear, while events involving danger, food and social betrayal are preserved and even exaggerated. After five retellings, very different readers converge on remarkably similar versions.",
        "Researchers have traced some tale types through centuries of written records, building family trees exactly as biologists do for species. One study concluded that a well-known tale of a supernatural helper is at least four thousand years old, far older than the earliest text that records it.",
        "Critics of the evolutionary approach argue that it explains the survival of stories but not their meaning, and that reducing a myth to a bundle of memorable features misses what matters most to the people who tell it. Even sympathetic scholars concede that the method works best on simple folk tales and struggles with long literary works.",
        "Both sides agree on one thing: stories are not idle decoration. They are among the oldest technologies our species possesses, tools for storing warnings, values and knowledge in a form that copies itself from mind to mind across generations.",
      ),
    },
  ],
  groups: [
    {
      id: "r3-p1-tfng",
      type: "mcq",
      variant: "tfng",
      part: 1,
      instructions:
        "Do the following statements agree with the information given in the passage? Write TRUE, FALSE or NOT GIVEN.",
      questions: [
        { stem: "Ellen Marsh grew up in a town where clay was easily found.", options: "" },
        { stem: "Marsh completed her full course of study at art school.", options: "" },
        { stem: "Marsh built her first kiln herself.", options: "" },
        { stem: "Critics immediately praised her early pots.", options: "" },
        { stem: "A gallery gave Marsh her first commercial success.", options: "" },
        { stem: "The copper red glaze failed in most firings.", options: "" },
        { stem: "Marsh's kiln is now displayed in the capital's art museum.", options: "" },
      ],
    },
    {
      id: "r3-p1-completion",
      type: "pasted",
      part: 1,
      instructions: "Complete the sentences below. Write ONE WORD ONLY from the passage for each answer.",
      text: P(
        "Marsh's home town depended economically on its 8_____.",
        "She left art school because pottery was treated as a minor 9_____.",
        "Her first workshop was set up in a disused 10_____.",
        "A department store ordered two hundred sets of plain 11_____.",
        "Her famous glaze required starving the kiln of 12_____.",
        "In later life she insisted students master 13_____ before style.",
      ),
    },
    {
      id: "r3-p2-headings",
      type: "headings",
      part: 2,
      instructions:
        "The passage has seven paragraphs. Choose the correct heading for each paragraph from the list below and drag it into the gap above the paragraph.",
      options: [
        "A limitation the designers accept openly",
        "How the device works",
        "A problem of affordability and a possible answer",
        "Why sunshine and scarcity overlap",
        "Results from real households",
        "The key improvement over older designs",
        "Use in disaster relief",
        "The history of solar power",
        "Competing commercial products",
        "Government regulation of water quality",
      ].join("\n"),
    },
    {
      id: "r3-p2-summary",
      type: "pasted",
      part: 2,
      instructions: "Complete the summary below. Write ONE WORD ONLY from the passage for each answer.",
      title: "The purifier in brief",
      text: P(
        "The device looks like a slim 21_____ and uses only sunlight. Water crosses a dark absorber in a thin 22_____, and the vapour condenses on the cover. A stack of layers reuses 23_____ that older stills wasted. Trials showed the output met international 24_____, though users must rinse away a crust of 25_____ each week. In emergencies the device needs no fuel, spare parts or 26_____.",
      ),
    },
    {
      id: "r3-p3-endings",
      type: "drag-text",
      part: 3,
      instructions: "Complete each sentence with the correct ending, A–F, below. Drag the correct ending into each gap.",
      text: P(
        `Similar tales appear in societies ${G}`,
        `In retelling experiments, unimportant details ${G}`,
        `Events involving danger or betrayal are ${G}`,
        `One tale of a supernatural helper is ${G}`,
        `Critics say the evolutionary method struggles with ${G}`,
      ),
      options: [
        "with no known contact.",
        "tend to disappear.",
        "preserved and exaggerated.",
        "at least four thousand years old.",
        "long literary works.",
        "recorded only in Europe.",
      ].join("\n"),
    },
    {
      id: "r3-p3-summarybox",
      type: "drag-text",
      part: 3,
      instructions: "Complete the summary using the list of words, A–I, below. Drag the correct word into each gap.",
      title: "Stories as organisms",
      text: P(
        `The evolutionary approach treats stories as things that are ${G} each time they are told.`,
        `Retellings introduce ${G}, just as copying introduces mutation.`,
        `Stories compete for human ${G} and memory.`,
        `Researchers build family ${G} of tales as biologists do for species.`,
        `Stories can be seen as ancient ${G} for storing knowledge.`,
      ),
      options: ["copied", "variation", "attention", "trees", "technologies", "meaning", "decoration", "warnings", "species"].join("\n"),
    },
    {
      id: "r3-p3-mcq",
      type: "mcq",
      variant: "single",
      part: 3,
      instructions: "Choose the correct letter, A, B, C or D.",
      questions: [
        {
          stem: "The writer presents the similarity of stories across cultures as",
          options: ["a coincidence.", "a puzzle to explain.", "a modern invention.", "a translation error."].join("\n"),
        },
        {
          stem: "In the chain-retelling experiments, the versions produced by different readers",
          options: ["grew steadily longer.", "became more varied.", "converged on similar forms.", "lost all their events."].join("\n"),
        },
        {
          stem: "What concession do sympathetic scholars make about the evolutionary method?",
          options: [
            "It cannot date any stories.",
            "It works poorly on simple folk tales.",
            "It struggles with long literary works.",
            "It ignores laboratory evidence.",
          ].join("\n"),
        },
        {
          stem: "Both sides in the debate agree that stories are",
          options: [
            "idle decoration.",
            "tools for storing knowledge.",
            "impossible to study.",
            "younger than writing.",
          ].join("\n"),
        },
      ],
    },
  ],
  answersRaw: [
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    "FALSE",
    "TRUE",
    "FALSE",
    "brickworks",
    "craft",
    "stable",
    "tableware",
    "oxygen",
    "materials",
    "Why sunshine and scarcity overlap",
    "How the device works",
    "The key improvement over older designs",
    "Results from real households",
    "A problem of affordability and a possible answer",
    "Use in disaster relief",
    "A limitation the designers accept openly",
    "suitcase",
    "film",
    "heat",
    "standards",
    "salt",
    "training",
    "with no known contact.",
    "tend to disappear.",
    "preserved and exaggerated.",
    "at least four thousand years old.",
    "long literary works.",
    "copied",
    "variation",
    "attention",
    "trees",
    "technologies",
    "B",
    "C",
    "C",
    "B",
  ].join("\n"),
};

// ============================================================================
// Sample 4 — TFNG · short answers · table (merged cells) · matching headings ·
//            TFNG · MCQ · sentence endings · YNNG
// ============================================================================

const READING_4: AuthoredTest = {
  module: "reading",
  name: "Full Reading Test — Sample 4",
  status: "draft",
  startNumber: 1,
  readingPassages: [
    {
      title: "Harvesting the rains",
      passage: P(
        "In the dry regions of the world, rain is not scarce so much as badly timed. Months of drought are broken by storms that deliver a year's water in an afternoon, most of it running uselessly away. For thousands of years, communities in these regions have built structures to catch the flood and keep it: tanks, terraces, and underground cisterns.",
        "The most elaborate systems developed on the trade routes of the ancient world, where towns grew in places with no rivers at all. Streets were graded so that every drop of rain moved toward a central reservoir, and house roofs drained through clay pipes into private cisterns below the floors. Inscriptions record laws that punished anyone who let rainwater escape their land.",
        "Such systems demanded constant care. Silt had to be dug from the tanks each year before the rains, channels swept, and rooftop gutters patched. The work was communal and compulsory, organised by rotas that in some towns survived for centuries. When colonial administrations replaced local rule, the rotas often lapsed, and within a generation many tanks were choked and abandoned.",
        "Modern engineers, faced with falling water tables, are returning to these old designs. In one district, the restoration of four hundred village tanks raised well levels measurably within five years and turned seasonal migration, once a necessity of the dry months, into a memory. The technology is simple; what is being rebuilt, hydrologists point out, is the institution of shared maintenance.",
      ),
    },
    {
      title: "The age of the railway",
      passage: P(
        "It is hard now to imagine the shock of the first railways. Before them, no human being had travelled faster than a galloping horse; within a generation, ordinary passengers were covering distances in an afternoon that had once taken a week.",
        "The engineering came first. Iron rails, steam traction and the techniques of cutting and embankment had all existed separately; the achievement of the early railway builders was to combine them into a system and to build that system across entire countries in a few frantic decades.",
        "The money followed. Railway construction consumed capital on a scale no industry had ever demanded, and it invented much of modern finance in the process: the joint-stock boom, the professional engineer's report, and the speculative crash all took their modern forms in railway shares.",
        "Time itself was reorganised. Every town had kept its own clock, set by the local noon; the railway timetable made that impossible. Station clocks, telegraphed from the capital, imposed a single national time on countries that had never needed one before.",
        "Food and cities changed together. Fresh milk, fish and vegetables could now travel overnight, and the great cities, freed from dependence on their immediate countryside, grew past every earlier limit. The suburb, the seaside resort and the commuter all appeared within twenty years of the first passenger line.",
        "Not everyone welcomed the change. Landowners fought the surveyors, doctors warned that the human body could not endure such speeds, and essayists mourned a countryside sliced by embankments. The objections slowed almost nothing.",
        "The railway also rewrote war and politics. Armies could be moved by timetable, and governments discovered that whoever controlled the junctions controlled the country. More happily, cheap excursion trains gave industrial workers their first sight of the sea.",
        "By the century's end the network was complete, and the railway had become what it remains in much of the world: not a marvel but a utility, noticed only when it fails. The deepest changes, historians argue, were the invisible ones — in clocks, in markets, and in the assumption that distance is measured in hours.",
      ),
    },
    {
      title: "The psychology of teamwork",
      passage: P(
        "Organisations everywhere organise their work in teams, on the assumption that groups outperform individuals. Research over several decades suggests the truth is less flattering: teams often perform below the sum of their parts, and the reasons are more psychological than technical.",
        "One well-documented problem is social loafing, the tendency of individuals to reduce effort when their contribution is hidden inside a group result. The effect grows with team size and shrinks sharply when each member's output is visible, which is why several researchers argue that the most reliable way to improve a team is simply to make individual contributions identifiable.",
        "A second problem is the way teams handle information. In discussion, groups spend most of their time on facts everyone already knows, while the crucial detail held by a single member often never surfaces. Structured techniques, such as asking each member to write independently before speaking, measurably increase the amount of unique information that reaches the table.",
        "The composition of a team matters less than its habits. Studies that tracked hundreds of working groups found that the strongest predictor of performance was not the intelligence of the members but the evenness of conversational turn-taking: teams in which a few voices dominated reliably underperformed, whatever the talent of those voices.",
        "None of this means teams are a mistake. Some tasks are simply too large for individuals, and well-run groups provide error-checking, motivation and a diversity of perspective no individual can match. The lesson of the research is narrower: teamwork is a skill to be designed and practised, not a default to be assumed.",
      ),
    },
  ],
  groups: [
    {
      id: "r4-p1-tfng",
      type: "mcq",
      variant: "tfng",
      part: 1,
      instructions:
        "Do the following statements agree with the information given in the passage? Write TRUE, FALSE or NOT GIVEN.",
      questions: [
        { stem: "In dry regions, most storm rainwater was traditionally lost.", options: "" },
        { stem: "The most elaborate harvesting systems grew up beside large rivers.", options: "" },
        { stem: "Some ancient laws punished the waste of rainwater.", options: "" },
        { stem: "Tank maintenance was carried out by paid professionals.", options: "" },
        { stem: "Restoring village tanks raised local well levels.", options: "" },
      ],
    },
    {
      id: "r4-p1-short",
      type: "pasted",
      part: 1,
      instructions: "Answer the questions below. Write ONE WORD ONLY from the passage for each answer.",
      text: P(
        "What material were the pipes that drained ancient roofs made of? 6_____",
        "What had to be dug out of the tanks every year? 7_____",
        "What kind of migration ended after the tanks were restored? 8_____",
      ),
    },
    {
      id: "r4-p1-table",
      type: "pasted",
      part: 1,
      instructions: "Complete the table below. Write ONE WORD AND/OR A NUMBER from the passage for each answer.",
      html: [
        "<table><tbody>",
        '<tr><th colspan="3">Water harvesting, ancient and modern</th></tr>',
        "<tr><th>Period</th><th>Feature</th><th>Detail</th></tr>",
        '<tr><td rowspan="2"><b>Ancient towns</b></td><td>streets</td><td>graded to move rain toward a central 9_____</td></tr>',
        "<tr><td>houses</td><td>private cisterns built below the 10_____</td></tr>",
        '<tr><td rowspan="2"><b>Modern district</b></td><td>restoration</td><td>11_____ village tanks restored</td></tr>',
        "<tr><td>result</td><td>well levels rose within 12_____ years</td></tr>",
        '<tr><td colspan="2"><b>Key to success</b></td><td>rebuilding the institution of shared 13_____</td></tr>',
        "</tbody></table>",
      ].join(""),
    },
    {
      id: "r4-p2-headings",
      type: "headings",
      part: 2,
      instructions:
        "The passage has eight paragraphs. Choose the correct heading for each paragraph from the list below and drag it into the gap above the paragraph.",
      options: [
        "Opposition that failed to stop progress",
        "A shock without precedent",
        "Standardising the nation's clocks",
        "From marvel to background utility",
        "Combining known techniques into a system",
        "New ways of feeding and housing millions",
        "Military and political consequences",
        "The invention of modern finance",
        "The decline of canal transport",
        "Railway architecture and design",
        "The training of engine drivers",
      ].join("\n"),
    },
    {
      id: "r4-p2-tfng",
      type: "mcq",
      variant: "tfng",
      part: 2,
      instructions:
        "Do the following statements agree with the information given in the passage? Write TRUE, FALSE or NOT GIVEN.",
      questions: [
        { stem: "Before railways, no one had travelled faster than a galloping horse.", options: "" },
        { stem: "Railway building required little capital compared with other industries.", options: "" },
        { stem: "Doctors expressed concerns about the effects of railway speed.", options: "" },
        { stem: "Excursion trains were too expensive for industrial workers.", options: "" },
        { stem: "Most railway companies of the period eventually merged.", options: "" },
      ],
    },
    {
      id: "r4-p3-mcq",
      type: "mcq",
      variant: "single",
      part: 3,
      instructions: "Choose the correct letter, A, B, C or D.",
      questions: [
        {
          stem: "According to the writer, research on teams shows that they",
          options: [
            "always outperform individuals.",
            "often perform below the sum of their parts.",
            "fail for mainly technical reasons.",
            "work best without any structure.",
          ].join("\n"),
        },
        {
          stem: "Social loafing becomes weaker when",
          options: [
            "teams are enlarged.",
            "rewards are shared equally.",
            "individual contributions are visible.",
            "tasks are made simpler.",
          ].join("\n"),
        },
        {
          stem: "In group discussions, crucial information held by one member",
          options: [
            "is usually discussed first.",
            "often never surfaces.",
            "is always written down.",
            "causes most disagreements.",
          ].join("\n"),
        },
        {
          stem: "The strongest predictor of team performance was found to be",
          options: [
            "the intelligence of members.",
            "the size of the team.",
            "even conversational turn-taking.",
            "the experience of the leader.",
          ].join("\n"),
        },
      ],
    },
    {
      id: "r4-p3-endings",
      type: "drag-text",
      part: 3,
      instructions: "Complete each sentence with the correct ending, A–G, below. Drag the correct ending into each gap.",
      text: P(
        `Social loafing grows with ${G}`,
        `Writing ideas independently before speaking increases ${G}`,
        `Teams dominated by a few voices reliably ${G}`,
        `Well-run groups provide error-checking and ${G}`,
        `The research suggests teamwork is a skill to be ${G}`,
      ),
      options: [
        "team size.",
        "unique information.",
        "underperform.",
        "a diversity of perspective.",
        "designed and practised.",
        "individual rewards.",
        "the cost of meetings.",
      ].join("\n"),
    },
    {
      id: "r4-p3-ynng",
      type: "mcq",
      variant: "ynng",
      part: 3,
      instructions:
        "Do the following statements agree with the claims of the writer? Write YES, NO or NOT GIVEN.",
      questions: [
        { stem: "Organisations assume that groups outperform individuals.", options: "" },
        { stem: "Team composition matters more than team habits.", options: "" },
        { stem: "Some tasks are too large for individuals to complete alone.", options: "" },
        { stem: "Teams should be abandoned in favour of individual work.", options: "" },
        { stem: "Most managers are aware of the research on teams.", options: "" },
      ],
    },
  ],
  answersRaw: [
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    "TRUE",
    "clay",
    "silt",
    "seasonal",
    "reservoir",
    "floors",
    "400 / four hundred",
    "5 / five",
    "maintenance",
    "A shock without precedent",
    "Combining known techniques into a system",
    "The invention of modern finance",
    "Standardising the nation's clocks",
    "New ways of feeding and housing millions",
    "Opposition that failed to stop progress",
    "Military and political consequences",
    "From marvel to background utility",
    "TRUE",
    "FALSE",
    "TRUE",
    "FALSE",
    "NOT GIVEN",
    "B",
    "C",
    "B",
    "C",
    "team size.",
    "unique information.",
    "underperform.",
    "a diversity of perspective.",
    "designed and practised.",
    "YES",
    "NO",
    "YES",
    "NO",
    "NOT GIVEN",
  ].join("\n"),
};

// ============================================================================
// Sample 5 — TFNG · flowchart · notes · summary from box ×2 · YNNG ×2 · MCQ ×2
// ============================================================================

const READING_5: AuthoredTest = {
  module: "reading",
  name: "Full Reading Test — Sample 5",
  status: "draft",
  startNumber: 1,
  readingPassages: [
    {
      title: "Fuel from an invasive weed",
      passage: P(
        "The floating fern salvinia arrived in the lake a decade ago, probably from a garden pond, and found conditions perfect. Within three years it covered a third of the water's surface in a mat thick enough to stop boats, block sunlight and suffocate the fishery beneath.",
        "Conventional responses failed one after another. Herbicides threatened the lake's drinking-water role, mechanical harvesters broke down faster than the weed grew back, and an imported beetle that eats salvinia elsewhere declined to thrive in the local climate.",
        "The turning point came from an energy researcher who saw the mats not as waste but as a crop. Salvinia, dried and compressed, burns well, and the lake was producing hundreds of tonnes of it a month for free.",
        "A pilot plant now operates on the shore. Fishermen paid by weight deliver fresh weed to a ramp, where it is chopped and spread on drying racks in the sun. The dried material is fed through a press that forms it into dense briquettes, which are sold as cooking fuel in the nearby town for less than the price of charcoal.",
        "The scheme's accounts are startling. The fishery is recovering as open water returns, household fuel costs have fallen, and the plant employs forty people in a district with few jobs. The weed has not been eliminated, and the plant's managers privately hope it never is: their fuel supply depends on the invader they were hired to fight.",
        "Ecologists watch that irony carefully. The scheme is a success, they agree, but its incentives must be designed so that no one is ever tempted to plant salvinia in the next lake.",
      ),
    },
    {
      title: "Growing up with many languages",
      passage: P(
        "In much of the world, growing up with three or four languages is not an achievement but a fact of daily life. A child may speak one language at home, a second in the market, a third at school, switching between them so fluidly that the question 'what is your native language?' has no simple answer.",
        "For most of the twentieth century, educational theory treated this as a problem. Multilingual children were expected to lag, their mental resources supposedly divided between competing systems. The research that eventually tested this assumption found something closer to the opposite: on tasks measuring attention and mental flexibility, multilingual children matched or outperformed their monolingual peers.",
        "The classroom, however, often works against them. In many countries, schooling is delivered in a single official language that may be the third or fourth language of the children in the room. Studies consistently find that children taught to read first in a familiar language learn faster, and later transfer the skill to the official language more successfully, than children plunged directly into an unfamiliar one.",
        "Reformers have translated this evidence into mother-tongue schooling programmes, and the early results are strong: enrolment rises, dropout falls, and test scores in the official language itself improve within a few years. The obstacles are practical rather than scientific: training teachers in many languages and printing books in languages that may never have been printed before is expensive and slow.",
        "Linguists add a further argument. Schooling that ignores small languages hastens their extinction, and each loss takes with it an archive of local knowledge. The classroom, they argue, is where the world's linguistic diversity will either be carried forward or quietly dropped.",
      ),
    },
    {
      title: "The revival of hand-crafted maps",
      passage: P(
        "In an age when every phone contains a map of the world, a small number of workshops are busier than they have been in decades doing something apparently obsolete: drawing maps by hand.",
        "Their customers are varied. Universities commission ceremonial maps of their campuses, novelists order maps of imaginary countries for their books, and private buyers, the largest group, want their own farms, voyages or family histories set down in ink and watercolour.",
        "The appeal, workshop owners say, is precisely what digital maps exclude. A hand-drawn map is selective: it shows the oak tree a family picnics under and leaves out the motorway, and its errors and emphases record a human judgement about what matters. One cartographer describes her work as portraiture, with the landscape as the sitter.",
        "The craft itself nearly died. When the last generation of commercial map engravers retired in the 1980s, their skills went with them, and today's practitioners are largely self-taught from manuals and museum collections. The revival has been fed, unexpectedly, by the internet, where time-lapse videos of lettering and coastline work attract audiences of millions and, from among them, apprentices.",
        "The workshops are small businesses with long order books. A commissioned map takes between three weeks and a year, and prices reflect the hours. None of the owners expects the craft to be more than a niche, and none seems troubled by this. The phone map answers the question of where things are, one of them observes; the drawn map answers the question of what a place means.",
      ),
    },
  ],
  groups: [
    {
      id: "r5-p1-tfng",
      type: "mcq",
      variant: "tfng",
      part: 1,
      instructions:
        "Do the following statements agree with the information given in the passage? Write TRUE, FALSE or NOT GIVEN.",
      questions: [
        { stem: "Salvinia probably entered the lake from a garden pond.", options: "" },
        { stem: "The weed covered the whole lake within three years.", options: "" },
        { stem: "Herbicides were rejected partly because the lake supplies drinking water.", options: "" },
        { stem: "The imported beetle failed to thrive in the local climate.", options: "" },
        { stem: "The briquettes cost more than charcoal.", options: "" },
        { stem: "The plant employs forty people.", options: "" },
        { stem: "Ecologists have demanded the plant be closed.", options: "" },
      ],
    },
    {
      id: "r5-p1-flow",
      type: "flowchart",
      part: 1,
      instructions:
        "Complete the flowchart below. Choose THREE answers from the box and drag the correct answer into each gap.",
      title: "From weed to fuel",
      steps: [
        `Fishermen deliver fresh weed and are paid by ${G}.`,
        `The chopped weed is dried on racks in the ${G}.`,
        `A press forms the dried material into dense ${G}.`,
      ],
      options: ["weight", "sun", "briquettes", "volume", "ovens", "pellets"].join("\n"),
    },
    {
      id: "r5-p1-notes",
      type: "pasted",
      part: 1,
      instructions: "Complete the notes below. Write ONE WORD ONLY from the passage for each answer.",
      text: P(
        "Open water is returning and the 11_____ is recovering.",
        "The plant's managers depend on the 12_____ they were hired to fight.",
        "Incentives must not tempt anyone to 13_____ salvinia elsewhere.",
      ),
    },
    {
      id: "r5-p2-summarybox",
      type: "drag-text",
      part: 2,
      instructions:
        "Complete the summary using the list of words, A–J, below. Drag the correct word into each gap.",
      title: "Multilingual childhood",
      text: P(
        `In many regions, speaking several languages is a fact of daily ${G}.`,
        `Twentieth-century theory expected multilingual children to ${G}.`,
        `In fact they matched or outperformed monolingual peers on tasks of ${G}.`,
        `Many children are schooled in a language that is not ${G} to them.`,
        `Children taught to read first in a familiar language learn ${G}.`,
        `The obstacles to reform are practical rather than ${G}.`,
      ),
      options: [
        "life",
        "lag",
        "attention",
        "familiar",
        "faster",
        "scientific",
        "official",
        "expensive",
        "flexible",
        "divided",
      ].join("\n"),
    },
    {
      id: "r5-p2-ynng",
      type: "mcq",
      variant: "ynng",
      part: 2,
      instructions:
        "Do the following statements agree with the claims of the writer? Write YES, NO or NOT GIVEN.",
      questions: [
        { stem: "Early educational theory about multilingual children was proved right.", options: "" },
        { stem: "Mother-tongue schooling improves results in the official language too.", options: "" },
        { stem: "Printing books in small languages is inexpensive.", options: "" },
        { stem: "Schooling choices affect the survival of small languages.", options: "" },
      ],
    },
    {
      id: "r5-p2-mcq",
      type: "mcq",
      variant: "single",
      part: 2,
      instructions: "Choose the correct letter, A, B, C or D.",
      questions: [
        {
          stem: "The question 'what is your native language?' is described as",
          options: [
            "easy for most children.",
            "having no simple answer for some children.",
            "central to school enrolment.",
            "a recent invention.",
          ].join("\n"),
        },
        {
          stem: "Mother-tongue schooling programmes have led to",
          options: [
            "rising enrolment and falling dropout.",
            "lower test scores at first.",
            "opposition from parents.",
            "larger class sizes.",
          ].join("\n"),
        },
        {
          stem: "According to linguists, the loss of a small language also removes",
          options: [
            "a source of teacher training.",
            "an archive of local knowledge.",
            "a barrier to development.",
            "a cause of school dropout.",
          ].join("\n"),
        },
      ],
    },
    {
      id: "r5-p3-summarybox",
      type: "drag-text",
      part: 3,
      instructions:
        "Complete the summary using the list of words, A–J, below. Drag the correct word into each gap.",
      title: "The drawn map",
      text: P(
        `Hand-drawn maps appeal because they are ${G}: they include what matters to the buyer.`,
        `One cartographer compares her maps to ${G}.`,
        `The craft nearly vanished when the last commercial ${G} retired.`,
        `Today's practitioners are largely ${G}.`,
        `The revival has been helped by videos on the ${G}.`,
        `A commissioned map can take up to a ${G} to finish.`,
      ),
      options: [
        "selective",
        "portraiture",
        "engravers",
        "self-taught",
        "internet",
        "year",
        "accurate",
        "printers",
        "month",
        "expensive",
      ].join("\n"),
    },
    {
      id: "r5-p3-ynng",
      type: "mcq",
      variant: "ynng",
      part: 3,
      instructions:
        "Do the following statements agree with the claims of the writer? Write YES, NO or NOT GIVEN.",
      questions: [
        { stem: "Private buyers form the largest group of customers.", options: "" },
        { stem: "Digital maps show a landscape more selectively than drawn maps.", options: "" },
        { stem: "Workshop owners expect the craft to become a mass industry.", options: "" },
        { stem: "Most workshop owners studied cartography at university.", options: "" },
      ],
    },
    {
      id: "r5-p3-mcq",
      type: "mcq",
      variant: "single",
      part: 3,
      instructions: "Choose the correct letter, A, B, C or D.",
      questions: [
        {
          stem: "Universities commission hand-drawn maps of",
          options: ["imaginary countries.", "their campuses.", "family histories.", "shipping routes."].join("\n"),
        },
        {
          stem: "The skills of the old map engravers",
          options: [
            "were recorded on video.",
            "were taught in universities.",
            "disappeared when they retired.",
            "were sold to the workshops.",
          ].join("\n"),
        },
        {
          stem: "The writer ends by contrasting where things are with",
          options: [
            "how much maps cost.",
            "what a place means.",
            "who owns the land.",
            "when maps were made.",
          ].join("\n"),
        },
        {
          stem: "The overall tone of the passage is best described as",
          options: ["alarmed.", "dismissive.", "appreciative.", "undecided."].join("\n"),
        },
      ],
    },
  ],
  answersRaw: [
    "TRUE",
    "FALSE",
    "TRUE",
    "TRUE",
    "FALSE",
    "TRUE",
    "NOT GIVEN",
    "weight",
    "sun",
    "briquettes",
    "fishery",
    "invader / weed",
    "plant",
    "life",
    "lag",
    "attention",
    "familiar",
    "faster",
    "scientific",
    "NO",
    "YES",
    "NO",
    "YES",
    "B",
    "A",
    "B",
    "selective",
    "portraiture",
    "engravers",
    "self-taught",
    "internet",
    "year",
    "YES",
    "NO",
    "NO",
    "NOT GIVEN",
    "B",
    "C",
    "B",
    "C",
  ].join("\n"),
};

// ============================================================================
// Sample 6 — sentence completion · TFNG ×2 · diagram labelling ·
//            matching info · table (merged cells) · matching people
// ============================================================================

const READING_6: AuthoredTest = {
  module: "reading",
  name: "Full Reading Test — Sample 6",
  status: "draft",
  startNumber: 1,
  readingPassages: [
    {
      title: "Farming on city rooftops",
      passage: P(
        "The flat roofs of a modern city add up to a surprising area of unused land, and a growing movement wants to farm it. Rooftop farms now operate on supermarkets, schools and disused factories, growing vegetables metres above the traffic.",
        "The advantages are real. Produce grown on a supermarket roof travels by lift rather than lorry, arriving on the shelves within hours of harvest. The soil layer insulates the building beneath, cutting heating and cooling costs, and the plants absorb storm rainfall that would otherwise surge into the drains.",
        "The difficulties are equally real. A saturated soil bed is heavy, and most existing roofs were never designed for the load, so farms must either use shallow, lightweight growing media or be limited to the minority of buildings with reinforced structures. Wind at roof height batters crops that would thrive at ground level, and every kilogram of compost must go up in a lift.",
        "The economics are tight but improving. High-value, fast-turnover crops, salads, herbs and berries, suit the shallow beds, and restaurants pay a premium for produce picked the same morning. Several farms balance their books with a second business, running tours, courses and rooftop dinners among the vegetable beds.",
        "City governments have begun to help, with grants for structural surveys and, in a few districts, rules requiring new flat-roofed buildings to be built farm-ready, with the load capacity and water connections included from the start. Advocates argue the goal is not for cities to feed themselves, which no one thinks possible, but to shorten the supply of the freshest foods, green the skyline, and reconnect urban people with growing.",
      ),
    },
    {
      title: "The boat lift at Marental",
      passage: P(
        "For two centuries, boats travelling the canal between the lowland ports and the upland industrial towns faced a wearying obstacle at Marental: a hillside that the canal climbed through a staircase of eleven locks. Passing the flight took a full day, consumed enormous quantities of water, and created queues that could last longer than the passage itself.",
        "The lift that replaced the locks is a machine of elegant simplicity. Two enormous water-filled tubs, each large enough to hold a barge, hang in a steel frame like the pans of a balance. When a boat enters the upper tub, gates seal, and a small pump adjusts the water level until the upper side is very slightly heavier. Released, the heavy tub descends and its twin rises, the two linked so that one almost perfectly counterweights the other.",
        "Because the tubs balance, the energy needed is astonishingly small: the motors that control the descent use about as much electricity per cycle as a family house does in a day. A journey that once took a day now takes eight minutes, and the water loss of the lock flight has been eliminated, since the tubs carry their water with them.",
        "The lift quickly became more than infrastructure. Its glass-sided machine hall and viewing galleries draw more visitors than the boats it carries, and the operators, who once measured success in tonnes of freight, now count café receipts with equal satisfaction.",
      ),
    },
    {
      title: "Engineering a cooler planet",
      passage: P(
        "A  As efforts to cut greenhouse-gas emissions fall behind what the climate requires, a once-fringe field has moved into the scientific mainstream: geoengineering, the deliberate, planet-scale modification of the climate system.",
        "B  Its proposals fall into two families. The first seeks to remove carbon dioxide from the air, whether by machines, minerals or forests; the second seeks to reflect a fraction of incoming sunlight, cooling the planet without changing the air's composition at all.",
        "C  Among removal schemes, the most discussed are direct air capture, in which fans push air through chemical filters, and enhanced weathering, in which crushed rock is spread on fields to absorb carbon dioxide as it slowly dissolves. Both work; both are at present enormously expensive per tonne removed.",
        "D  Reflection schemes are cheaper and faster, and that is precisely what worries researchers. Injecting fine particles into the upper atmosphere would measurably cool the planet within years, at a cost within the reach of a single large country, but the cooling would be uneven, the side effects on rainfall are poorly understood, and the particles would need renewing indefinitely.",
        "E  The governance problem may exceed the technical one. Sunlight falls on everyone; a scheme that improved one region's harvests while drying another's monsoon would be an act with no precedent in international law, and no treaty currently exists to authorise, forbid or even monitor it.",
        "F  Field research remains tiny and contested. A single high-altitude balloon experiment, involving a few kilograms of harmless mineral dust, was cancelled after public protest, and researchers complain that the resulting knowledge gap is itself a danger: if reflection is ever attempted in an emergency, it will be attempted blind.",
        "G  Advocates and critics agree on one point: no geoengineering scheme replaces the need to cut emissions. Removal is too slow and reflection too risky to substitute for decarbonisation; at best they might shave the peak from warming already unavoidable.",
        "H  The field's researchers describe their own work with unusual ambivalence, as insurance they hope will never be claimed. The purpose of studying planetary cooling, one of them has written, is to ensure that if humanity ever reaches for the thermostat, it does so with open eyes.",
      ),
    },
  ],
  groups: [
    {
      id: "r6-p1-sentences",
      type: "pasted",
      part: 1,
      instructions:
        "Complete the sentences below. Write NO MORE THAN TWO WORDS from the passage for each answer.",
      text: P(
        "Rooftop produce can reach a supermarket's shelves by 1_____ rather than lorry.",
        "The soil layer 2_____ the building underneath.",
        "The plants absorb 3_____ that would otherwise flood the drains.",
        "Most existing roofs were not designed for the 4_____ of saturated soil.",
        "Crops at roof height are battered by 5_____.",
        "Restaurants pay a premium for produce picked the same 6_____.",
        "Some districts require new flat-roofed buildings to be built 7_____.",
      ),
    },
    {
      id: "r6-p1-tfng",
      type: "mcq",
      variant: "tfng",
      part: 1,
      instructions:
        "Do the following statements agree with the information given in the passage? Write TRUE, FALSE or NOT GIVEN.",
      questions: [
        { stem: "Rooftop farms operate only on new buildings.", options: "" },
        { stem: "Shallow growing beds suit fast-turnover crops.", options: "" },
        { stem: "Some rooftop farms earn money from tours and dinners.", options: "" },
        { stem: "City grants are available for structural surveys in some places.", options: "" },
        { stem: "Advocates claim cities could feed themselves entirely.", options: "" },
        { stem: "Rooftop farming began in North America.", options: "" },
      ],
    },
    {
      id: "r6-p2-tfng",
      type: "mcq",
      variant: "tfng",
      part: 2,
      instructions:
        "Do the following statements agree with the information given in the passage? Write TRUE, FALSE or NOT GIVEN.",
      questions: [
        { stem: "The lock staircase at Marental contained eleven locks.", options: "" },
        { stem: "Queues at the locks sometimes lasted longer than the passage itself.", options: "" },
        { stem: "The two tubs of the lift counterweight each other.", options: "" },
        { stem: "The lift uses more electricity than the locks did water.", options: "" },
        { stem: "The lift was designed by a local engineer.", options: "" },
        { stem: "The lift attracts more visitors than boats.", options: "" },
      ],
    },
    {
      id: "r6-p2-diagram",
      type: "picture",
      part: 2,
      instructions:
        "Label the diagram below. Write ONE WORD from the passage for each answer. (Add your own diagram image above the labels.)",
      title: "How the boat lift works",
      text: P(
        `Two water-filled ${G} hang in a steel frame.`,
        `The frame acts like the pans of a ${G}.`,
        `When a boat enters, the ${G} are sealed.`,
        `A small ${G} adjusts the water level.`,
        `The heavier side is released and ${G}, raising its twin.`,
        `Each cycle uses about as much electricity as a family ${G} in a day.`,
        `A passage that took a day now takes eight ${G}.`,
      ),
    },
    {
      id: "r6-p3-matchinfo",
      type: "table",
      part: 3,
      instructions:
        "The passage has eight paragraphs, A–H. Which paragraph contains the following information? Select the correct letter, A–H.",
      rows: [
        "why a cancelled experiment leaves a dangerous gap in knowledge",
        "the two families that geoengineering proposals fall into",
        "a legal vacuum surrounding planetary-scale schemes",
      ].join("\n"),
      cols: "A\nB\nC\nD\nE\nF\nG\nH",
    },
    {
      id: "r6-p3-table",
      type: "pasted",
      part: 3,
      instructions: "Complete the table below. Write ONE WORD from the passage for each answer.",
      html: [
        "<table><tbody>",
        '<tr><th colspan="3">Two approaches to geoengineering</th></tr>',
        "<tr><th>Approach</th><th>Example</th><th>Drawback</th></tr>",
        '<tr><td rowspan="2"><b>Carbon removal</b></td><td>fans push air through chemical 30_____</td><td rowspan="2">very 31_____ per tonne removed</td></tr>',
        "<tr><td>crushed 32_____ spread on fields</td></tr>",
        '<tr><td rowspan="3"><b>Sunlight reflection</b></td><td rowspan="3">fine 33_____ injected into the upper atmosphere</td><td>cooling would be 34_____</td></tr>',
        "<tr><td>effects on 35_____ poorly understood</td></tr>",
        "<tr><td>particles need renewing 36_____</td></tr>",
        "</tbody></table>",
      ].join(""),
    },
    {
      id: "r6-p3-people",
      type: "table",
      part: 3,
      instructions:
        "Look at the following statements and the list of researchers: A — Dr Ana Ferro; B — Prof. Jun Sato; C — Dr Malin Ek; D — Prof. David Osei. Match each statement with the correct researcher, A–D.",
      rows: [
        "Reflection schemes could be afforded by a single large country.",
        "Studying planetary cooling is insurance we hope never to claim.",
        "No scheme replaces the need to cut emissions.",
        "An emergency attempt at reflection would be made blind.",
      ].join("\n"),
      cols: "A\nB\nC\nD",
    },
  ],
  answersRaw: [
    "lift",
    "insulates",
    "storm rainfall / rainfall",
    "load / weight",
    "wind",
    "morning",
    "farm-ready",
    "FALSE",
    "TRUE",
    "TRUE",
    "TRUE",
    "FALSE",
    "NOT GIVEN",
    "TRUE",
    "TRUE",
    "TRUE",
    "NOT GIVEN",
    "NOT GIVEN",
    "TRUE",
    "tubs",
    "balance",
    "gates",
    "pump",
    "descends",
    "house",
    "minutes",
    "F",
    "B",
    "E",
    "filters",
    "expensive",
    "rock",
    "particles",
    "uneven",
    "rainfall",
    "indefinitely",
    "A",
    "D",
    "C",
    "B",
  ].join("\n"),
};

export const READING_TEMPLATES: ReadingTemplate[] = [
  { id: "r-sample-1", label: "Sample 1 — TFNG · matching info · choose TWO · summary box", test: READING_1 },
  { id: "r-sample-2", label: "Sample 2 — TFNG · matching info · matching people · endings", test: READING_2 },
  { id: "r-sample-3", label: "Sample 3 — matching headings · summary box · endings · MCQ", test: READING_3 },
  { id: "r-sample-4", label: "Sample 4 — headings · table · short answers · endings", test: READING_4 },
  { id: "r-sample-5", label: "Sample 5 — flowchart · summary box ×2 · YNNG · MCQ", test: READING_5 },
  { id: "r-sample-6", label: "Sample 6 — sentence completion · diagram · table · people", test: READING_6 },
];
